<?php
/* @var $this Lesite_Slider_Block_Slider */
?>
<?php if ($this->canShow()): ?>
    <ul id="slider-<?php echo $this->getSliderId() ?>" class="slider">
        <?php foreach ($this->getSlides() as $slide): ?>
            <?php /* @var $slide Lesite_Slider_Model_Slide */ ?>
            <li id="slide-<?php echo $slide->getId() ?>" class="slide">
                <div class="image">
                    <img src="<?php echo $slide->getImageUrl() ?>" alt="<?php echo $slide->getImageAlt(); ?>" title="<?php echo $slide->getImageAlt(); ?>" />
                </div>
                <div class="body">
                    <h4 class="name"><?php echo $this->escapeHtml($slide->getName()) ?></h4>
                    <div class="content"><?php echo $slide->getContent() ?></div>
                </div>
                <div class="buttons-set">
                    <?php foreach (array(1, 2) as $index): ?>
                        <?php $category = $this->getCategory($slide->getButtonCategoryId($index)) ?>
                        <?php if ($category): ?>
                            <a class="button" href="<?php echo $category->getUrl(); ?>">
                                <span><span><?php echo $this->escapeHtml($slide->getButtonLabel($index)) ?></span></span>
                            </a>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </div>
            </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
