<?php
/**
 * @var $this Lesite_Local_Block_Product_Feed
 */
?>
<?php if ($this->getProducts()): ?>
    <ul class="product-feed">
        <?php foreach ($this->getProducts() as $product): ?>
            <?php /* @var $product Mage_Catalog_Model_Product */ ?>
            <li class="product">
                <div class="product-image">
                    <img src="<?php echo $this->getImageUrl($product) ?>" alt="<?php echo $this->escapeHtml($this->getImageLabel($product)) ?>" title="<?php echo $this->escapeHtml($this->getImageLabel($product)) ?>" width="<?php echo $this->getImageWidth() ?>" height="<?php echo $this->getImageHeight() ?>" />
                </div>
                <div class="product-name">
                    <h4><?php echo $product->getName() ?></h4>
                </div>
                <?php echo $this->getPriceHtml($product); ?>
            </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
